<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'easyadmin.listener.exception' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/EventListener/ExceptionListener.php';
include_once $this->targetDirs[3].'/vendor/easycorp/easyadmin-bundle/src/EventListener/ExceptionListener.php';

return $this->services['easyadmin.listener.exception'] = new \EasyCorp\Bundle\EasyAdminBundle\EventListener\ExceptionListener(($this->services['twig'] ?? $this->load('getTwigService.php')), $this->parameters['easyadmin.config'], 'easyadmin.listener.exception:showExceptionPageAction', ($this->privates['logger'] ?? ($this->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())));
