<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV9Rt9G8\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV9Rt9G8/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerV9Rt9G8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerV9Rt9G8\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerV9Rt9G8\srcApp_KernelProdContainer(array(
    'container.build_hash' => 'V9Rt9G8',
    'container.build_id' => 'fe44f581',
    'container.build_time' => 1548162292,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerV9Rt9G8');
