#index:
#    path: /
#    controller: App\Controller\DefaultController::index
connexion:
    path: /
    controller: 'App\Controller\SecurityController::connexion'

deconnexion:
    path: /logout
    controller: App\Controller\SecurityController::logout

